// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/active-worker": {
            "get": {
                "description": "-",
                "summary": "Inicia o Worker",
                "responses": {
                    "200": {
                        "description": "Worker Executado com sucesso",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao executar worker",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/send-email": {
            "post": {
                "description": "Envia um e-mail para o destinatário especificado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Envia um e-mail",
                "parameters": [
                    {
                        "description": "Dados do e-mail",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/email.EmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "E-mail enviado com sucesso",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Payload inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao enviar e-mail",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "email.EmailRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "example": "Este é um exemplo"
                },
                "subject": {
                    "type": "string",
                    "example": "Hello World"
                },
                "to": {
                    "type": "string",
                    "example": "recipient@example.com"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Sender API",
	Description:      "Esta é uma API para enviar e-mails.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
